### ISSUE TITLE
License with open code but restricted copyright

### ISSUE THREAD

**Issue by mariusz-malinowski** [Switajski/FlexibleOrders#27]
We need to find a license which:
- makes whole code open,
- allows third parties to contribute with our permission,
- gives us exclusive right to sell the licensed software,
- allows commercial users, who received our permission, to modify the code for their own commercial use,
- doesn't allow commercial use by third parties without our permission,
- doesn't allow commercial distribution of original/modified code by third parties without our permission.

License to check:
Apache License 2.0 (http://en.wikipedia.org/wiki/Apache_License)
GNU GPL 3.0 (http://en.wikipedia.org/wiki/GNU_General_Public_License)
AGPL (http://en.wikipedia.org/wiki/Affero_General_Public_License)
LGPL (http://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)
Openbravo license (http://www.openbravo.com/license-business-model/)

**Comment by Switajski** [comment]
Leave it completely open source (Propably MIT), after replacing ExtJs with an open source Javscript Framework, like AngularJS.
